### ISSUE TITLE
Breaking REST API

### ISSUE THREAD

**Issue by noraconley** [rezen/auditor#1]
When I access any rest endpoint, I receive this error:

```Fatal error: Class 'Auditor\WP_REST_Server' not found in .../wp-content/plugins/auditor/Auditor/AuditRouter.php on line 51```

Using ```global $wp_rest_server``` seems to fix this issue.

WordPress 4.7.3

**Comment by rezen** [comment]
🤦‍ doh! I should have had you review this earlier, oh well!

https://github.com/rezen/auditor/commit/099af0bdf9f18c2b6e3185cac90a5535cc683abe
